---
# tasks file for ntpd

- name: set OS related variables
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml'
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'
    - defaults.yml

- name: enable to ntpdate service
  service:
    name: '{{ ntpdate_service }}'
    enabled: yes
  when: 
    - ntpdate_service|default(false)
