---
- name: Set OS related variables
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'
    - defaults.yml

- name: Enable to ntpdate service
  ansible.builtin.service:
    name: '{{ ntpdate_service }}'
    enabled: true
  when:
    - ntpdate_service|default(false)
